Optimize acyclic_coloring
gdalle/SparseMatrixColorings.jl pull request #52
Opened 2024-08-09 21:29 UTC by amontoison

2024-08-10 05:51 UTC, gdalle requested changes

2024-08-10 05:51 UTC, gdalle commented on src/graph.jl
> +nedges(g::Graph) = nnz(g) ÷ 2
Only true for graphs which have empty diagonals, which is not the case with Jacobian coloring

2024-08-10 05:58 UTC, gdalle commented on src/graph.jl
> +nedges(g::Graph) = nnz(g) ÷ 2
I'll remove these functions for now

2024-08-10 05:59 UTC, gdalle approved these changes

2024-08-10 06:01 UTC, merged

2024-08-12 03:46 UTC, amontoison commented
@gdalle 
I have the result of all benchmarks tonight:
```julia
Problem 1/38: pwtk
size(A) = (217918, 217918) | nnz(A) = 11524432
Column coloring: 180
timer: 1.79020499
Star coloring: 108
timer: 13.128444092
Acyclic coloring: 53
timer: 10.576655852

Problem 2/38: Lin
size(A) = (256000, 256000) | nnz(A) = 1766400
Column coloring: 12
timer: 0.416505455
Star coloring: 11
timer: 0.571455992
Acyclic coloring: 7
timer: 0.679195734

Problem 3/38: bmw3_2
size(A) = (227362, 227362) | nnz(A) = 11288630
Column coloring: 336
timer: 1.909149565
Star coloring: 135
timer: 12.342920864
Acyclic coloring: 71
timer: 7.814760165

Problem 4/38: fcondp2
size(A) = (201822, 201822) | nnz(A) = 11294316
Column coloring: 120
timer: 1.629666569
Star coloring: 111
timer: 12.638892798
Acyclic coloring: 66
timer: 9.962901677

Problem 5/38: halfb
size(A) = (224617, 224617) | nnz(A) = 12387821
Column coloring: 141
timer: 1.787561872
Star coloring: 117
timer: 13.807083961
Acyclic coloring: 60
timer: 9.373287101

Problem 6/38: hood
size(A) = (220542, 220542) | nnz(A) = 9895422
Column coloring: 103
timer: 1.600294055
Star coloring: 89
timer: 9.353391648
Acyclic coloring: 55
timer: 7.042590133

Problem 7/38: troll
size(A) = (213453, 213453) | nnz(A) = 11985111
Column coloring: 387
timer: 1.776546394
Star coloring: 108
timer: 15.771867829
Acyclic coloring: 57
timer: 11.172261877

Problem 8/38: CO
size(A) = (221119, 221119) | nnz(A) = 7666057
Column coloring: 380
timer: 1.098667786
Star coloring: 264
timer: 10.609647166
Acyclic coloring: 152
timer: 10.034654336

Problem 9/38: Ga41As41H72
size(A) = (268096, 268096) | nnz(A) = 18488476
Column coloring: 837
timer: 9.074174242
Star coloring: 565
timer: 182.222612823
Acyclic coloring: 391
timer: 42.176475158

Problem 10/38: Si87H76
size(A) = (240369, 240369) | nnz(A) = 10661631
Column coloring: 560
timer: 2.414487114
Star coloring: 283
timer: 31.736568593
Acyclic coloring: 176
timer: 17.317734069

Problem 11/38: BenElechi1
size(A) = (245874, 245874) | nnz(A) = 13150496
Column coloring: 78
timer: 2.017972905
Star coloring: 71
timer: 15.331120981
Acyclic coloring: 42
timer: 11.372123778

Problem 12/38: 3Dspectralwave2
size(A) = (292008, 292008) | nnz(A) = 12935272
Column coloring: 202
timer: 2.544826437
Star coloring: 102
timer: 23.922568767
Acyclic coloring: 39
timer: 21.942924515

Problem 13/38: thermomech_dM
size(A) = (204316, 204316) | nnz(A) = 1423116
Column coloring: 15
timer: 0.166520177
Star coloring: 11
timer: 0.939707582
Acyclic coloring: 7
timer: 0.426854618

Problem 14/38: offshore
size(A) = (259789, 259789) | nnz(A) = 4242673
Column coloring: 48
timer: 0.713105461
Star coloring: 29
timer: 2.755919986
Acyclic coloring: 14
timer: 2.444392949

Problem 15/38: citationCiteseer
size(A) = (268495, 268495) | nnz(A) = 2313294
Column coloring: 1318
timer: 1.174781763
Star coloring: 213
timer: 4.72819425
Acyclic coloring: 65
timer: 5.304618855

Problem 16/38: coAuthorsCiteseer
size(A) = (227320, 227320) | nnz(A) = 1628268
Column coloring: 1372
timer: 0.225162009
Star coloring: 106
timer: 1.35290398
Acyclic coloring: 87
timer: 1.622949863

Problem 17/38: coAuthorsDBLP
size(A) = (299067, 299067) | nnz(A) = 1955352
Column coloring: 336
timer: 0.352591368
Star coloring: 128
timer: 1.804727382
Acyclic coloring: 115
timer: 2.229698357

Problem 18/38: delaunay_n18
size(A) = (262144, 262144) | nnz(A) = 1572792
Column coloring: 23
timer: 0.09778755
Star coloring: 17
timer: 0.578770509
Acyclic coloring: 7
timer: 0.565640443

Problem 19/38: kron_g500-logn18
size(A) = (262144, 262144) | nnz(A) = 21165908
Column coloring: 49163
timer: 309.510867972
Star coloring: 4310
timer: 2552.233228622
Acyclic coloring: 1978
timer: 2286.58141312

Problem 20/38: rgg_n_2_18_s0
size(A) = (262144, 262144) | nnz(A) = 3094566
Column coloring: 35
timer: 0.242767916
Star coloring: 27
timer: 1.539946026
Acyclic coloring: 19
timer: 1.372478875

Problem 21/38: m14b
size(A) = (214765, 214765) | nnz(A) = 3358036
Column coloring: 42
timer: 0.695000404
Star coloring: 32
timer: 2.418476703
Acyclic coloring: 18
timer: 1.97721004

Problem 22/38: HTC_336_4438
size(A) = (226340, 226340) | nnz(A) = 783496
Column coloring: 7393
timer: 0.670305142
Star coloring: 7394
timer: 1.025649588
Acyclic coloring: 7393
timer: 18.691909322

Problem 23/38: HTC_336_9129
size(A) = (226340, 226340) | nnz(A) = 762969
Column coloring: 7393
timer: 0.43779486
Star coloring: 7394
timer: 0.927538927
Acyclic coloring: 7393
timer: 17.519127616

Problem 24/38: CurlCurl_1
size(A) = (226451, 226451) | nnz(A) = 2472071
Column coloring: 25
timer: 0.184289404
Star coloring: 18
timer: 0.835749483
Acyclic coloring: 10
timer: 0.872502701

Problem 25/38: al2010
size(A) = (252266, 252266) | nnz(A) = 1230482
Column coloring: 76
timer: 0.099341865
Star coloring: 26
timer: 0.451601529
Acyclic coloring: 9
timer: 0.439798963

Problem 26/38: az2010
size(A) = (241666, 241666) | nnz(A) = 1196094
Column coloring: 137
timer: 0.118326504
Star coloring: 23
timer: 0.626197685
Acyclic coloring: 9
timer: 0.515600282

Problem 27/38: co2010
size(A) = (201062, 201062) | nnz(A) = 974574
Column coloring: 120
timer: 0.077927899
Star coloring: 27
timer: 0.329383883
Acyclic coloring: 8
timer: 0.328657502

Problem 28/38: ga2010
size(A) = (291086, 291086) | nnz(A) = 1418056
Column coloring: 85
timer: 0.106496096
Star coloring: 20
timer: 0.595135744
Acyclic coloring: 10
timer: 0.750242026

Problem 29/38: ia2010
size(A) = (216007, 216007) | nnz(A) = 1021170
Column coloring: 49
timer: 0.13893868
Star coloring: 20
timer: 0.631229113
Acyclic coloring: 8
timer: 0.312675323

Problem 30/38: in2010
size(A) = (267071, 267071) | nnz(A) = 1281716
Column coloring: 54
timer: 0.098204586
Star coloring: 17
timer: 0.614488292
Acyclic coloring: 8
timer: 0.593226184

Problem 31/38: ks2010
size(A) = (238600, 238600) | nnz(A) = 1121798
Column coloring: 54
timer: 0.080683371
Star coloring: 22
timer: 0.487037616
Acyclic coloring: 7
timer: 0.364857674

Problem 32/38: la2010
size(A) = (204447, 204447) | nnz(A) = 980634
Column coloring: 581
timer: 0.074684536
Star coloring: 22
timer: 0.509073618
Acyclic coloring: 11
timer: 0.350915202

Problem 33/38: mn2010
size(A) = (259777, 259777) | nnz(A) = 1227102
Column coloring: 311
timer: 0.0967323
Star coloring: 20
timer: 0.53852985
Acyclic coloring: 9
timer: 0.539063858

Problem 34/38: nc2010
size(A) = (288987, 288987) | nnz(A) = 1416620
Column coloring: 83
timer: 0.109021197
Star coloring: 21
timer: 0.680753053
Acyclic coloring: 11
timer: 0.711910232

Problem 35/38: ok2010
size(A) = (269118, 269118) | nnz(A) = 1274148
Column coloring: 65
timer: 0.098862618
Star coloring: 22
timer: 0.720965241
Acyclic coloring: 8
timer: 0.504435829

Problem 36/38: tn2010
size(A) = (240116, 240116) | nnz(A) = 1193966
Column coloring: 89
timer: 0.104763846
Star coloring: 24
timer: 0.747861327
Acyclic coloring: 9
timer: 0.41374581

Problem 37/38: va2010
size(A) = (285762, 285762) | nnz(A) = 1402128
Column coloring: 102
timer: 0.110662316
Star coloring: 21
timer: 0.521112078
Acyclic coloring: 11
timer: 0.793464474

Problem 38/38: wi2010
size(A) = (253096, 253096) | nnz(A) = 1209404
Column coloring: 60
timer: 0.094892928
Star coloring: 21
timer: 0.586021114
Acyclic coloring: 10
timer: 0.401114694
```